name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        nvim_tag: [nightly, v0.11.0]
    name: ${{ matrix.os }} / ${{ matrix.nvim_tag }}
    runs-on: ${{ matrix.os }}
    env:
      NVIM: ${{ matrix.os == 'windows-latest' && 'nvim-win64\\bin\\nvim.exe' || 'nvim' }}

    steps:
      - name: Checkout ðŸ“‹
        uses: actions/checkout@v6

      - name: Install Tree-sitter ðŸŒ³
        uses: tree-sitter/setup-action/cli@v2

      - name: Prepare Neovim ðŸš§
        env:
          NVIM_TAG: ${{ matrix.nvim_tag }}
        run: |
          bash ./scripts/dependencies.sh
          bash ./scripts/ci-install.sh

      - name: Run tests ðŸ§ª
        run: |
          $NVIM --version
          make test

