name: Issue Autoresponder

on:
  issues:
    types: [opened]

jobs:
  auto-response:
    runs-on: ubuntu-latest

    steps:
    - uses: derekprior/add-autoresponse@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        respondableId: ${{ github.event.issue.node_id }}
        response: |
            > [!IMPORTANT]
            > If your issue does **NOT** contain a valid `minimal.lua` then this issue _may_ be closed without a response.
            > Thanks for respecting my time and efforts.

            Thanks @${{ github.event.issue.user.login }}. I'll get to this as soon as I can.

            In the meantime, please ensure:

            - This is a plugin related issue and not an issue with your configuration
            - You've searched for similar issues (try the [discussions](https://github.com/olimorris/codecompanion.nvim/discussions) too)
            - You've checked out the [documentation](https://codecompanion.olimorris.dev)
            - The issue title is accurate
            - There is a valid `minimal.lua` file included so I can try and recreate the issue
        author: ${{ github.event.issue.user.login }}
        exemptedAuthors: "olimorris, GitMurf, S1M0N38, bassamsdata"
