name: Update Sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: 0 21 * * 0-6

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Generate Sponsors ğŸ’–
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.SPONSORS_TOKEN }}
          file: "README.md"
          active-only: true
          include-private: true
        if: ${{ github.repository == 'olimorris/codecompanion.nvim' }}

      - name: Create Pull Request ğŸš€
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs: update sponsors in README.md"
          title: "Update Sponsors in README"
          labels: "ignore-for-release"
          delete-branch: true
